import { APIGuild, APIGuildMember, APIMessage, GatewayMessageCreateDispatchData } from "@discordjs/core";
import { Message } from "..";

export interface ListEvents {
    ApplicationCommandPermissionsUpdate : [  ],
    EntitlementCreate: [  ],
    EntitlementDelete: [  ],
    EntitlementUpdate: [  ],
    GuildMemberRoleUpdate: [  ],
    ChannelCreate : [  ],
    ChannelDelete : [  ],
    ChannelPinsUpdate : [  ],
    ChannelUpdate : [  ],
    GuildBanAdd : [  ],
    GuildBanRemove : [  ],
    GuildCreate : [  ],
    GuildDelete : [  ],
    GuildEmojisUpdate : [  ],
    GuildIntegrationsUpdate : [  ],
    GuildMemberAdd : [  ],
    GuildMemberRemove : [  ],
    GuildMembersChunk : [  ],
    GuildMemberUpdate : [  ],
    GuildRoleCreate : [  ],
    GuildRoleDelete : [  ],
    GuildRoleUpdate : [  ],
    GuildStickersUpdate : [  ],
    GuildUpdate : [  ],
    IntegrationCreate : [  ],
    IntegrationDelete : [  ],
    IntegrationUpdate : [  ],
    InteractionCreate : [  ],
    InviteCreate : [  ],
    InviteDelete : [  ],
    MessageCreate : [ Message ],
    MessageDelete : [  ],
    MessageDeleteBulk : [  ],
    MessageReactionAdd : [  ],
    MessageReactionRemove : [  ],
    MessageReactionRemoveAll : [  ],
    MessageReactionRemoveEmoji : [  ],
    MessageUpdate : [  ],
    PresenceUpdate : [  ],
    StageInstanceCreate : [  ],
    StageInstanceDelete : [  ],
    StageInstanceUpdate : [  ],
    Ready : [ ],
    Resumed : [  ],
    ThreadCreate : [  ],
    ThreadDelete : [  ],
    ThreadListSync : [  ],
    ThreadMembersUpdate : [  ],
    ThreadMemberUpdate : [  ],
    ThreadUpdate : [  ],
    TypingStart : [  ],
    UserUpdate : [  ],
    VoiceServerUpdate : [  ],
    VoiceStateUpdate : [  ],
    WebhooksUpdate : [  ],
    GuildScheduledEventCreate : [  ],
    GuildScheduledEventUpdate : [  ],
    GuildScheduledEventDelete : [  ],
    GuildScheduledEventUserAdd : [  ],
    GuildScheduledEventUserRemove : [  ],
    AutoModerationRuleCreate : [  ],
    AutoModerationRuleUpdate : [  ],
    AutoModerationRuleDelete : [  ],
    AutoModerationActionExecution : [  ],
    GuildAuditLogEntryCreate : [  ],
};


export type EventsHandler =  {
    [K in keyof ListEvents]: (...args: ListEvents[K]) => unknown;
};


export type MessageOptions =  GatewayMessageCreateDispatchData;