# This is a basic workflow to help you get started with Actions

name: Deno Changes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Git_Push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Deno Charge
        run: deno fmt && deno fmt --no-semicolons
        
      - name: Git add
        run: git add . 
        
      - name: Git commit
        run: git commit -m "Deno Change"

      - name: Git push
        run: git push
